
paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos OK desde la DB
        "500":
          description: Error interno del servidor
    post:
      summary: Crea un producto (Solo puede hacerlo el admin o un usuario premium)
      tags:
        - Products
      responses:
        "201":
          description: Producto creado Ok en la DB
        "500":
          description: Error interno del servidor
    put:
      summary: Modifica un producto (Solo puede hacerlo el admin o un usuario premiun respecto de su producto)
      tags:
        - Products
      responses:
        "201":
          description: Producto modificado Ok en la DB
        "500":
          description: Error interno del servidor
    delete:
      summary: Elimina un producto de la DB (Solo puede hacerlo el admin o un usuario premiun respecto de su producto)
      tags:
        - Products
      responses:
        "201":
          description: Producto eliminado en la DB
        "500":
          description: Error interno del servidor